[GenData]
    Geometry = "cube" # Cube or flat
    nparticles = 10000
    nruns = 100
    OutputFolderPath = "/nevis/milne/files/ms6556/BleekerData/GramsMLRecoData/Train"
    OutputFileBaseName = "AnodeImagesTrain"
    PixelCountX = 10
    PixelCountY = 10
[TrainData]
    BaseTrainName = "AnodeImagesTrain"
    InputTrainingFolderPath = "/nevis/milne/files/ms6556/BleekerData/GramsMLRecoData/Train"
    BaseValidationName = "AnodeImagesVal"
    InputValidationFolderPath = "/nevis/milne/files/ms6556/BleekerData/GramsMLRecoData/Validation"
    BaseTestName = "AnodeImagesTest"
    InputTestFolderPath = "/nevis/milne/files/ms6556/BleekerData/GramsMLRecoData/Test"
